// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3DPrintsAPP.Data;

#nullable disable

namespace _3DPrintsASP.NETCoreMVCAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217095509_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrintFilament", b =>
                {
                    b.Property<int>("PrintId")
                        .HasColumnType("int");

                    b.Property<int>("FilamentId")
                        .HasColumnType("int");

                    b.HasKey("PrintId", "FilamentId");

                    b.HasIndex("FilamentId");

                    b.ToTable("PrintFilaments");

                    b.HasData(
                        new
                        {
                            PrintId = 1,
                            FilamentId = 1
                        },
                        new
                        {
                            PrintId = 1,
                            FilamentId = 3
                        },
                        new
                        {
                            PrintId = 2,
                            FilamentId = 2
                        },
                        new
                        {
                            PrintId = 3,
                            FilamentId = 3
                        },
                        new
                        {
                            PrintId = 4,
                            FilamentId = 2
                        },
                        new
                        {
                            PrintId = 4,
                            FilamentId = 5
                        },
                        new
                        {
                            PrintId = 5,
                            FilamentId = 1
                        });
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Filament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<decimal>("Diameter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FilamentColor")
                        .HasColumnType("int");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double>("WeightKG")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.ToTable("Filaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = 11,
                            Diameter = 1.75m,
                            FilamentColor = 7,
                            Material = 1,
                            PrinterId = 1,
                            UploadPhoto = "https://cdn2.botland.com.pl/127588-large_default/filament-bambu-lab-pc-175mm-1kg-w-zestawie-z-wielorazowa-szpula-black.jpg",
                            WeightKG = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Brand = 2,
                            Diameter = 1.75m,
                            FilamentColor = 8,
                            Material = 3,
                            PrinterId = 2,
                            UploadPhoto = "https://m.media-amazon.com/images/I/71eFciMUSaL._AC_UF1000,1000_QL80_.jpg",
                            WeightKG = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Brand = 11,
                            Diameter = 1.75m,
                            FilamentColor = 3,
                            Material = 1,
                            PrinterId = 1,
                            UploadPhoto = "https://cdncloudcart.com/20502/products/images/467/bambu-lab-pla-cf-filament-s-karbonovi-vlakna-1-75mm-1kg-za-3d-printeri-65708d0c52b7f_150x150.jpeg?1744983052",
                            WeightKG = 1.0
                        },
                        new
                        {
                            Id = 5,
                            Brand = 3,
                            Diameter = 1.75m,
                            FilamentColor = 9,
                            Material = 1,
                            PrinterId = 1,
                            UploadPhoto = "https://www.prusa3d.com/content/images/product/3146.jpg",
                            WeightKG = 0.75
                        },
                        new
                        {
                            Id = 6,
                            Brand = 2,
                            Diameter = 1.75m,
                            FilamentColor = 3,
                            Material = 5,
                            PrinterId = 1,
                            UploadPhoto = "https://ruumik.ee/wp-content/uploads/2021/01/tpu_Translucent-Blue-3.jpg",
                            WeightKG = 0.5
                        },
                        new
                        {
                            Id = 7,
                            Brand = 11,
                            Diameter = 1.75m,
                            FilamentColor = 1,
                            Material = 2,
                            PrinterId = 2,
                            UploadPhoto = "https://botland.com.pl/img/art/inne/24646_2.jpg",
                            WeightKG = 1.0
                        });
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Print", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeOnly>("PrintTime")
                        .HasColumnType("time");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.ToTable("Prints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Organizer for tools, nozzles and spare parts.",
                            PrintTime = new TimeOnly(2, 15, 0),
                            PrinterId = 1,
                            Title = "Desk Organizer",
                            UploadPhoto = "https://img1.yeggi.com/images-3d-model/86f/9869000_organizer-desktop-organizer-by-casperdesigns-makerworld-download-free-",
                            UploadedTime = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Simple mount for accessories and tools.",
                            PrintTime = new TimeOnly(1, 5, 0),
                            PrinterId = 2,
                            Title = "Wall Mount",
                            UploadPhoto = "https://fbi.cults3d.com/uploaders/16518072/illustration-file/34e80894-2287-4f98-ac0e-60b6e2086616/AR%20Mount%20v2%20v1.png",
                            UploadedTime = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Keeps cables organized on the desk.",
                            PrintTime = new TimeOnly(0, 45, 0),
                            PrinterId = 1,
                            Title = "Cable Holder",
                            UploadPhoto = "https://www.3dforprint.com/modelos/10243/cable-holder1.webp",
                            UploadedTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Compact phone stand for desk use.",
                            PrintTime = new TimeOnly(1, 20, 0),
                            PrinterId = 2,
                            Title = "Phone Stand",
                            UploadPhoto = "https://i.etsystatic.com/23796806/r/il/8180c7/5739653765/il_fullxfull.5739653765_is72.jpg",
                            UploadedTime = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Small tray for screws and tools.",
                            PrintTime = new TimeOnly(2, 50, 0),
                            PrinterId = 1,
                            Title = "Tool Tray",
                            UploadPhoto = "https://i.etsystatic.com/52313838/r/il/122c4d/6435355435/il_fullxfull.6435355435_cecf.jpg",
                            UploadedTime = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AMS")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NozzleDiameter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AMS = true,
                            Description = "Bambu Lab P1S with AMS for multi-color prints.",
                            ModelName = "Bambu Lab P1S",
                            NozzleDiameter = 1.75m,
                            UploadPhoto = "https://store.bblcdn.com/s7/default/7abb7477d233498b82a02dc93dd069df/P1.jpg",
                            UploadedTime = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AMS = false,
                            Description = "Reliable budget printer for starters and upgrades.",
                            ModelName = "Creality Ender 3",
                            NozzleDiameter = 1.75m,
                            UploadPhoto = "https://m.media-amazon.com/images/I/61CndtGd6wL._AC_UF350,350_QL80_.jpg",
                            UploadedTime = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrintFilament", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.Filament", "Filament")
                        .WithMany("PrintFilaments")
                        .HasForeignKey("FilamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintsAPP.Data.Models.Print", "Print")
                        .WithMany("PrintFilaments")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");

                    b.Navigation("Print");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Filament", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.Printer", "Printer")
                        .WithMany("Filaments")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Print", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.Printer", "Printer")
                        .WithMany("Prints")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Filament", b =>
                {
                    b.Navigation("PrintFilaments");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Print", b =>
                {
                    b.Navigation("PrintFilaments");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Printer", b =>
                {
                    b.Navigation("Filaments");

                    b.Navigation("Prints");
                });
#pragma warning restore 612, 618
        }
    }
}
