// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3DPrintsAPP.Data;

#nullable disable

namespace _3DPrintsASP.NETCoreMVCAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406125412_AddPrintRatings")]
    partial class AddPrintRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "admin-concurrency-stamp",
                            Email = "admin@site.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SITE.COM",
                            NormalizedUserName = "ADMIN@SITE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMgoypDgbqDzlnw4UlwgU6TYJT73IMHdtY2JV0a668gEYJDfxImXXZQSuODkFJHRWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "admin@site.com"
                        });
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Filament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<decimal>("Diameter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FilamentColor")
                        .HasColumnType("int");

                    b.Property<int>("FilamentOptionId")
                        .HasColumnType("int");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("WeightKG")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FilamentOptionId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("UserId");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.FilamentOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<decimal>("Diameter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FilamentColor")
                        .HasColumnType("int");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double>("WeightKG")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FilamentOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = 11,
                            Diameter = 1.75m,
                            FilamentColor = 7,
                            Material = 1,
                            UploadPhoto = "https://cdn2.botland.com.pl/127588-large_default/filament-bambu-lab-pc-175mm-1kg-w-zestawie-z-wielorazowa-szpula-black.jpg",
                            WeightKG = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Brand = 2,
                            Diameter = 1.75m,
                            FilamentColor = 8,
                            Material = 3,
                            UploadPhoto = "https://m.media-amazon.com/images/I/71eFciMUSaL._AC_UF1000,1000_QL80_.jpg",
                            WeightKG = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Brand = 11,
                            Diameter = 1.75m,
                            FilamentColor = 3,
                            Material = 1,
                            UploadPhoto = "https://cdncloudcart.com/20502/products/images/467/bambu-lab-pla-cf-filament-s-karbonovi-vlakna-1-75mm-1kg-za-3d-printeri-65708d0c52b7f_150x150.jpeg?1744983052",
                            WeightKG = 1.0
                        },
                        new
                        {
                            Id = 5,
                            Brand = 3,
                            Diameter = 1.75m,
                            FilamentColor = 9,
                            Material = 1,
                            UploadPhoto = "https://www.prusa3d.com/content/images/product/3146.jpg",
                            WeightKG = 0.75
                        },
                        new
                        {
                            Id = 6,
                            Brand = 2,
                            Diameter = 1.75m,
                            FilamentColor = 3,
                            Material = 5,
                            UploadPhoto = "https://ruumik.ee/wp-content/uploads/2021/01/tpu_Translucent-Blue-3.jpg",
                            WeightKG = 0.5
                        },
                        new
                        {
                            Id = 7,
                            Brand = 11,
                            Diameter = 1.75m,
                            FilamentColor = 1,
                            Material = 2,
                            UploadPhoto = "https://botland.com.pl/img/art/inne/24646_2.jpg",
                            WeightKG = 1.0
                        });
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Print", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("PrintTime")
                        .HasColumnType("time");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("UserId");

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.PrintRating", b =>
                {
                    b.Property<int>("PrintId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("PrintId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PrintRatings");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AMS")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NozzleDiameter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrinterOptionId")
                        .HasColumnType("int");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PrinterOptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.PrinterOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AMS")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NozzleDiameter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UploadPhoto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PrinterOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AMS = true,
                            Description = "Bambu Lab P1S with AMS for multi-color prints.",
                            ModelName = "Bambu Lab P1S",
                            NozzleDiameter = 1.75m,
                            UploadPhoto = "https://store.bblcdn.com/s7/default/7abb7477d233498b82a02dc93dd069df/P1.jpg",
                            UploadedTime = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AMS = false,
                            Description = "Reliable budget printer for starters and upgrades.",
                            ModelName = "Creality Ender 3",
                            NozzleDiameter = 1.75m,
                            UploadPhoto = "https://m.media-amazon.com/images/I/61CndtGd6wL._AC_UF350,350_QL80_.jpg",
                            UploadedTime = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.UserCollectionPrint", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PrintId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PrintId");

                    b.HasIndex("PrintId");

                    b.ToTable("UserCollectionPrints");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Filament", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.FilamentOption", "FilamentOption")
                        .WithMany("Filaments")
                        .HasForeignKey("FilamentOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3DPrintsAPP.Data.Models.Printer", null)
                        .WithMany("Filaments")
                        .HasForeignKey("PrinterId");

                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilamentOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Print", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.Printer", null)
                        .WithMany("Prints")
                        .HasForeignKey("PrinterId");

                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", "User")
                        .WithMany("Prints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.PrintRating", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.Print", "Print")
                        .WithMany("Ratings")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", "User")
                        .WithMany("PrintRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Print");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Printer", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.PrinterOption", "PrinterOption")
                        .WithMany("Printers")
                        .HasForeignKey("PrinterOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrinterOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.UserCollectionPrint", b =>
                {
                    b.HasOne("_3DPrintsAPP.Data.Models.Print", "Print")
                        .WithMany("UserCollectionPrints")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3DPrintsAPP.Data.Models.ApplicationUser", "User")
                        .WithMany("UserCollectionPrints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Print");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("PrintRatings");

                    b.Navigation("Prints");

                    b.Navigation("UserCollectionPrints");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.FilamentOption", b =>
                {
                    b.Navigation("Filaments");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Print", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("UserCollectionPrints");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.Printer", b =>
                {
                    b.Navigation("Filaments");

                    b.Navigation("Prints");
                });

            modelBuilder.Entity("_3DPrintsAPP.Data.Models.PrinterOption", b =>
                {
                    b.Navigation("Printers");
                });
#pragma warning restore 612, 618
        }
    }
}
